import logging

from models.schemas import IssueFixResult, SentryIssue
from services.github_service import GitHubService

logger = logging.getLogger(__name__)


def build_commit_message(issue_results: list[IssueFixResult]) -> str:
    """Build a single commit message covering all fixed issues."""
    fixed = [r for r in issue_results if r.status == "fixed"]
    lines = [f"fix: auto-fix {len(fixed)} Sentry issue(s)", ""]
    for r in fixed:
        lines.append(f"- #{r.issue_id}: {r.title}")
    return "\n".join(lines)


def build_pr_content(
    issue_results: list[IssueFixResult],
    all_issues: list[SentryIssue],
) -> tuple[str, str]:
    """Build PR title and description. Returns (title, body)."""
    fixed = [r for r in issue_results if r.status == "fixed"]
    failed = [r for r in issue_results if r.status == "failed"]

    # Classification scope tag in PR title (e.g. "fix(third-party):", "fix(flow):").
    # If all fixed issues agree on a classification, use it; mixed batches stay generic.
    classifications = {r.classification for r in fixed if r.classification}
    scope = ""
    if len(classifications) == 1:
        scope_map = {"third_party": "third-party", "flow": "flow", "misc": "misc"}
        scope = f"({scope_map.get(next(iter(classifications)), '')})"

    sentry_ids = ",".join(r.issue_id for r in fixed)
    suffix = f" [sentry: {sentry_ids}]" if sentry_ids else ""
    pr_title = f"fix{scope}: auto-fix {len(fixed)} Sentry issue(s){suffix}"

    body = [
        "## Summary",
        f"Automated fixes for **{len(fixed)}** Sentry issues.",
        f"- {len(failed)} issues could not be fixed\n",
        "## Issues Fixed",
    ]

    for r in fixed:
        issue = next((i for i in all_issues if i.id == r.issue_id), None)
        link = issue.permalink if issue and issue.permalink else ""
        files = ", ".join(f"`{f}`" for f in r.files_changed) if r.files_changed else "N/A"
        body.append(
            f"- **#{r.issue_id}**: {r.title} (confidence: {r.confidence})\n"
            f"  - Files: {files}\n"
            f"  - [View in Sentry]({link})"
        )

    # Test verification results — two layers per fix
    tested = [r for r in fixed if r.test_result]
    if tested:
        body.append("\n## Test Verification")
        body.append("Two layers run for every fix: a deterministic file-content check (always-on safety net) and an LLM-generated behavioral Jest+RTL test that exercises the user flow. `verified` reflects the behavioral layer.")

        body.append("\n### Deterministic layer (file-content check)")
        body.append("| Issue | Test File | Pre-Fix | Post-Fix | Status |")
        body.append("|-------|-----------|---------|----------|--------|")
        for r in tested:
            tr = r.test_result
            pre = "FAIL" if not tr.pre_fix_passed else "PASS"
            post = "PASS" if tr.post_fix_passed else "FAIL"
            status = "Verified" if tr.deterministic_verified else "Unverified"
            body.append(f"| #{r.issue_id} | `{tr.test_file}` | {pre} | {post} | {status} |")

        behavioral = [r for r in tested if r.test_result.behavioral_test_file]
        if behavioral:
            body.append("\n### Behavioral layer (LLM-generated, runs the user flow)")
            body.append("| Issue | Test File | Pre-Fix | Post-Fix | Repairs | Status |")
            body.append("|-------|-----------|---------|----------|---------|--------|")
            for r in behavioral:
                tr = r.test_result
                pre = "FAIL" if not tr.behavioral_pre_fix_passed else "PASS"
                post = "PASS" if tr.behavioral_post_fix_passed else "FAIL"
                status = "Verified" if tr.behavioral_verified else "Unverified"
                body.append(
                    f"| #{r.issue_id} | `{tr.behavioral_test_file}` | {pre} | {post} | "
                    f"{tr.behavioral_repair_attempts} | {status} |"
                )

            for r in behavioral:
                tr = r.test_result
                desc = tr.behavioral_test_description or "(no description)"
                body.append(f"\n<details><summary>Behavioral test for #{r.issue_id} — {desc}</summary>\n")
                body.append(f"\n```js\n{tr.behavioral_test_code}\n```\n")
                if tr.behavioral_post_fix_output and not tr.behavioral_post_fix_passed:
                    body.append(f"\n**Post-fix output (last 500 chars):**\n```\n{tr.behavioral_post_fix_output}\n```\n")
                body.append("</details>")

    if failed:
        body.append("\n## Issues Not Fixed")
        for r in failed:
            body.append(f"- **#{r.issue_id}**: {r.title} — {r.error}")

    body.append("\n---")
    body.append("🤖 Auto-generated by Sentry Automation Pipeline")

    return pr_title, "\n".join(body)


def commit_push_and_create_pr(
    github: GitHubService,
    branch_name: str,
    issue_results: list[IssueFixResult],
    all_issues: list[SentryIssue],
) -> str:
    """Commit all changes, push, and create a PR. Returns the PR URL."""
    # Commit and push
    commit_msg = build_commit_message(issue_results)
    logger.info(f"[PR_CREATOR] Committing:\n{commit_msg}")
    github.commit_and_push(branch_name, commit_msg)

    # Create PR
    pr_title, pr_body = build_pr_content(issue_results, all_issues)
    fixed_results = [r for r in issue_results if r.status == "fixed"]
    extra_labels = [f"sentry-issue-{r.issue_id}" for r in fixed_results]
    classifications = {r.classification for r in fixed_results if r.classification}
    extra_labels.extend(f"class-{c}" for c in classifications)
    logger.info(f"[PR_CREATOR] Creating PR: {pr_title}")
    pr_url = github.create_pull_request(
        branch_name=branch_name,
        pr_title=pr_title,
        pr_description=pr_body,
        extra_labels=extra_labels,
    )
    logger.info(f"[PR_CREATOR] ✓ PR created: {pr_url}")
    return pr_url
