import logging

from models.schemas import IssueFixResult, SentryIssue
from services.github_service import GitHubService

logger = logging.getLogger(__name__)


def build_commit_message(issue_results: list[IssueFixResult]) -> str:
    """Build a single commit message covering all fixed issues."""
    fixed = [r for r in issue_results if r.status == "fixed"]
    lines = [f"fix: auto-fix {len(fixed)} Sentry issue(s)", ""]
    for r in fixed:
        lines.append(f"- #{r.issue_id}: {r.title}")
    return "\n".join(lines)


def build_pr_content(
    issue_results: list[IssueFixResult],
    all_issues: list[SentryIssue],
) -> tuple[str, str]:
    """Build PR title and description. Returns (title, body)."""
    fixed = [r for r in issue_results if r.status == "fixed"]
    failed = [r for r in issue_results if r.status == "failed"]
    filtered = [r for r in issue_results if r.status == "filtered"]

    pr_title = f"fix: auto-fix {len(fixed)} Sentry issue(s)"

    body = [
        "## Summary",
        f"Automated fixes for **{len(fixed)}** Sentry issues.",
        f"- {len(filtered)} issues filtered as non-relevant (resolved in Sentry)",
        f"- {len(failed)} issues could not be fixed\n",
        "## Issues Fixed",
    ]

    for r in fixed:
        issue = next((i for i in all_issues if i.id == r.issue_id), None)
        link = issue.permalink if issue and issue.permalink else ""
        files = ", ".join(f"`{f}`" for f in r.files_changed) if r.files_changed else "N/A"
        body.append(
            f"- **#{r.issue_id}**: {r.title} (confidence: {r.confidence})\n"
            f"  - Files: {files}\n"
            f"  - [View in Sentry]({link})"
        )

    # Test verification results
    tested = [r for r in fixed if r.test_result]
    if tested:
        body.append("\n## Test Verification")
        body.append("| Issue | Test File | Pre-Fix | Post-Fix | Status |")
        body.append("|-------|-----------|---------|----------|--------|")
        for r in tested:
            tr = r.test_result
            pre = "FAIL" if not tr.pre_fix_passed else "PASS"
            post = "PASS" if tr.post_fix_passed else "FAIL"
            status = "Verified" if tr.verified else "Unverified"
            body.append(f"| #{r.issue_id} | `{tr.test_file}` | {pre} | {post} | {status} |")

    if filtered:
        body.append("\n## Filtered Issues (resolved in Sentry)")
        for r in filtered:
            body.append(f"- **#{r.issue_id}**: {r.title} — {r.error}")

    if failed:
        body.append("\n## Issues Not Fixed")
        for r in failed:
            body.append(f"- **#{r.issue_id}**: {r.title} — {r.error}")

    body.append("\n---")
    body.append("🤖 Auto-generated by Sentry Automation Pipeline")

    return pr_title, "\n".join(body)


def commit_push_and_create_pr(
    github: GitHubService,
    branch_name: str,
    issue_results: list[IssueFixResult],
    all_issues: list[SentryIssue],
) -> str:
    """Commit all changes, push, and create a PR. Returns the PR URL."""
    # Commit and push
    commit_msg = build_commit_message(issue_results)
    logger.info(f"[PR_CREATOR] Committing:\n{commit_msg}")
    github.commit_and_push(branch_name, commit_msg)

    # Create PR
    pr_title, pr_body = build_pr_content(issue_results, all_issues)
    logger.info(f"[PR_CREATOR] Creating PR: {pr_title}")
    pr_url = github.create_pull_request(
        branch_name=branch_name,
        pr_title=pr_title,
        pr_description=pr_body,
    )
    logger.info(f"[PR_CREATOR] ✓ PR created: {pr_url}")
    return pr_url
